# --------------------------------------------------------------------------------------------#
#                                  STABLE DIFFUSION EXTENSION                                 #
# This file contains the documentation and debug settings for the Stable Diffusion extension. #
# --------------------------------------------------------------------------------------------#

dark_theme: true
show_controls: true
mode: chat
chat_style: cai-chat
character: Assistant
preset: Debug-deterministic
seed: 1337
stream: true

default_extensions:
  - gallery
  - stable_diffusion

#----------------------#
# API ENDPOINT DETAILS #
#----------------------#

## Sets the API endpoint to use for generating images.
## If you are using the default stable-diffusion-webui settings, you do not need to change this.
stable_diffusion-api_endpoint: "http://127.0.0.1:7860/sdapi/v1"

## Leave as-is if you did not set up any authentication for the API.
stable_diffusion-api_username: ""
stable_diffusion-api_password: ""

#-----------------------------#
# IMAGE GENERATION PARAMETERS #
#-----------------------------#

stable_diffusion-default_prompt: "an adult female, close up, upper body, highlights in hair, brown eyes, wearing casual clothes, side light"
stable_diffusion-base_prompt_suffix: "high resolution, detailed, realistic, vivid"
stable_diffusion-base_negative_prompt: "ugly, disformed, disfigured, immature"
stable_diffusion-sampler_name: "UniPC"
stable_diffusion-sampling_steps: 15
stable_diffusion-denoising_strength: 0.7
stable_diffusion-width: 512
stable_diffusion-height: 512
stable_diffusion-cfg_scale: 7
stable_diffusion-clip_skip: 1
stable_diffusion-seed: -1

#------------------#
# USER PREFERENCES #
#------------------#

## Sets if generated images should be saved to the "outputs" folder inside the stable_diffusion extension directory.
stable_diffusion-save_images: true

## Defines how image generation should be triggered. Possible values:
##  - "continuous": Always generate images.
##  - "interactive": Generate images only if a message with a triggering text was sent.
##  - "manual": Generates images only if the image generation button was pressed. (WIP, not implemented yet)
stable_diffusion-trigger_mode: "interactive"

## Defines the trigger pattern to use for generating images in text mode.
stable_diffusion-interactive_mode_trigger_regex: "(?aims)(send|mail|message|me)\\b.+?\\b(image|pic(ture)?|photo|snap(shot)?|selfie|meme)s?\\b"

## Defines the subject of the message to generate images for in text mode.
stable_diffusion-interactive_mode_subject_regex: ".*\\s+of\\s+(.*)[\\.,!?]?"

## The prompt to trigger a description of the subject.
stable_diffusion-interactive_mode_description_prompt: >
  You are now a text generator for the Stable Diffusion AI image generator. You will generate a text prompt for it.

  Describe [subject] using comma-separated tags only. Do not use sentences.
  Include many tags such as tags for the environment, gender, clothes, age, location, light, daytime, angle, pose, etc.

  Do not write anything else. Do not ask any questions. Do not talk.

## The default subject to use if no subject was found in the message.
stable_diffusion-interactive_mode_default_subject: "your appearance, your surroundings and what you are doing right now"

## If enabled, will automatically unload the LLM model from VRAM and then load the SD model instead when generating images.
## After the image is generated, it will unload the SD model again and then reload the LLM model.
## Saves VRAM but will slow down generation speed. Only recommended if you have a low amount of VRAM or use very large models.
stable_diffusion-dynamic_vram_reallocation_enabled: false

## Do not stream messages if generating images at the same time. Improves generation speed.
stable_diffusion-dont_stream_when_generating_images: true

#-----------------#
# POST PROCESSING #
#-----------------#

## Sets if generated images should be upscaled.
stable_diffusion-upscaling_enabled: false

## Sets the upscaler to use for upscaling generated images.
## Some examples are: Latent, LDSR, RealESRGAN 4x+, Lanczos, Nearest, etc.
stable_diffusion-upscaling_upscaler: "RealESRGAN 4x+"

## Amount to upscale by (1 = 100%, 2 = 200%, etc.).
stable_diffusion-upscaling_scale: 2

## Sets if faces should be enhanced in generated images.
stable_diffusion-enhance_faces_enabled: false

#-------------#
# FACESWAPLAB #
#-------------#

## Face swapping using FaceSwapLab.
## Requires the sd-webui-faceswaplab extension to be installed.
## Repository: https://github.com/glucauze/sd-webui-faceswaplab

## Sets if faces should be swapped in generated images.
stable_diffusion-faceswaplab_enabled: true

## Only swap faces if same gender.
stable_diffusion-faceswaplab_same_gender_only: true

## If enabled, order source faces by size and swap biggest.
## Otherwise, order source faces from left to right and swap first face.
stable_diffusion-faceswaplab_sort_by_size: true

## Sets the source face to use for face swapping.
## It's possible to set it in 3 ways:
##   1. Local file: "file:///./example.jpg"
##   2. URL: "https://some-site.com/example.png"
##   3. (recommended) FaceSwapLab face checkpoint: "checkpoint://example"
##      You can see the list of available checkpoints in the "models/faceswaplab/faces" directory inside your Stable Diffusion WebUI directory.
##      See https://github.com/glucauze/sd-webui-faceswaplab#build-and-use-checkpoints- for more on how to create face checkpoints.
stable_diffusion-faceswaplab_source_face: "file:///./extensions/stable_diffusion/assets/example_face.jpg"

## Use the nth face in the source image as source face
stable_diffusion-faceswaplab_source_face_index: 0

## Sets if the face should be enhanced after swapping
stable_diffusion-faceswaplab_enhance_face_enabled: true

## Model to use for restoring the face (CodeFormer, GFPGAN)
stable_diffusion-faceswaplab_enhance_face_model: "CodeFormer"

## Visibility of the enhanced face (0.0 - 1.0)
stable_diffusion-faceswaplab_enhance_face_visibility: 1

## Weight of the CodeFormer model (0.0 - 1.0)
stable_diffusion-faceswaplab_enhance_face_codeformer_weight: 1

## Use the nth face in the target image as target face
stable_diffusion-faceswaplab_target_face_index: 0
